[manager]
cwd = { fg = "#00f0ff", bold = true }

hovered         = { fg = "#212121", bg = "#00f0ff", bold = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#eedb85", italic = true }
find_position = { fg = "#d867c6", bg = "transparent", bold = true }

marker_selected = { fg = "#51f66f", bg = "#51f66f" }
marker_copied   = { fg = "#eedb85", bg = "#eedb85" }
marker_cut      = { fg = "#f3505c", bg = "#f3505c" }

tab_active   = { fg = "#ffffff", bg = "#f3505c", bold = true }
tab_inactive = { fg = "#676767", bg = "#2a2a2a" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#333333" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#2a2a2a", bg = "#2a2a2a" }

mode_normal = { fg = "#212121", bg = "#00f0ff", bold = true }
mode_select = { fg = "#212121", bg = "#51f66f", bold = true }
mode_unset  = { fg = "#212121", bg = "#d867c6", bold = true }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#00f0ff", bg = "#2a2a2a" }
progress_error  = { fg = "#f3505c", bg = "#2a2a2a" }

permissions_t = { fg = "#368aec" }
permissions_r = { fg = "#eedb85" }
permissions_w = { fg = "#f3505c" }
permissions_x = { fg = "#51f66f" }
permissions_s = { fg = "#676767" }

[input]
border   = { fg = "#00f0ff" }
title    = { fg = "#00f0ff" }
value    = { fg = "#ffffff" }
selected = { bg = "#333333" }

[select]
border   = { fg = "#00f0ff" }
active   = { fg = "#f3505c", bold = true }
inactive = { fg = "#ffffff" }

[tasks]
border  = { fg = "#00f0ff" }
title   = { fg = "#00f0ff" }
hovered = { fg = "#212121", bg = "#00f0ff" }

[which]
mask            = { bg = "#212121" }
cand            = { fg = "#00f0ff" }
rest            = { fg = "#676767" }
desc            = { fg = "#d867c6" }
separator       = " ➜ "
separator_style = { fg = "#333333" }

[help]
on      = { fg = "#51f66f" }
run     = { fg = "#d867c6" }
desc    = { fg = "#ffffff" }
hovered = { bg = "#333333", bold = true }
footer  = { fg = "#212121", bg = "#cacaca" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#00f0ff" },
	{ mime = "video/*", fg = "#d867c6" },
	{ mime = "audio/*", fg = "#d867c6" },
	{ mime = "application/zip", fg = "#eedb85" },
	{ mime = "application/gzip", fg = "#eedb85" },
	{ mime = "application/x-tar", fg = "#eedb85" },
	{ mime = "application/x-bzip2", fg = "#eedb85" },
	{ mime = "application/x-7z-compressed", fg = "#eedb85" },
	{ mime = "application/x-rar", fg = "#eedb85" },
	{ mime = "application/pdf", fg = "#f3505c" },
]
