[window]
padding = { x = 0, y = 0 }
opacity = 1.0
decorations = "None"
startup_mode = "Maximized"

[keyboard]
bindings = [
    { key = "Q", mods = "Control", action = "Quit" },
    { key = "V", mods = "Control", action = "Paste" },
    { key = "C", mods = "Control", action = "Copy" },
    { key = "D", mods = "Control|Shift", chars = "\u001b[68;5u" },
]

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 11.0

[font.offset]
x = -1
y = -1

[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.15

[colors.primary]
background = "#212121"
foreground = "#cacaca"

[colors.cursor]
text = "#212121"
cursor = "#cacaca"

[colors.selection]
text = "#cacaca"
background = "#343434"

[colors.normal]
black   = "#212121"
red     = "#f3505c"
green   = "#51f66f"
yellow  = "#eedb85"
blue    = "#368aec"
magenta = "#d867c6"
cyan    = "#00f0ff"
white   = "#cacaca"

[colors.bright]
black   = "#676767"
red     = "#f3505c"
green   = "#51f66f"
yellow  = "#eedb85"
blue    = "#368aec"
magenta = "#d867c6"
cyan    = "#00f0ff"
white   = "#ffffff"

[selection]
save_to_clipboard = true

