# JetBrains Cyberpunk Palette
# Red: #f3505c, Green: #51f66f, Yellow: #eedb85, Blue: #368aec, Magenta: #d867c6, Cyan: #00f0ff

format = """[┌─>](bold #f3505c) [ $os$username ](bg:#00f0ff fg:#212121 bold)[ $directory ](bg:#f3505c fg:#ffffff bold)[$python$nodejs$rust$golang](bg:#368aec fg:#ffffff bold)[ $git_branch$git_status ](bg:#eedb85 fg:#212121 bold)
[│](bold #f3505c)
[└─>](bold #f3505c) """

add_newline = true

[os]
format = " $symbol "
style = "bg:#00f0ff fg:#212121 bold"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Gentoo = "󰣨"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:#00f0ff fg:#212121 bold"
style_root = "bg:#00f0ff fg:#212121 bold"
format = "$user "

[directory]
style = "bg:#f3505c fg:#ffffff bold"
format = " $path "

[python]
symbol = "󰌞 "
style = "bg:#368aec fg:#ffffff bold"
format = ' $symbol($version) '
disabled = false

[nodejs]
symbol = "󰌞 "
style = "bg:#368aec fg:#ffffff bold"
format = ' $symbol($version) '
disabled = false

[rust]
symbol = "󰘗 "
style = "bg:#368aec fg:#ffffff bold"
format = ' $symbol($version) '
disabled = false

[golang]
symbol = "󰟓 "
style = "bg:#368aec fg:#ffffff bold"
format = ' $symbol($version) '
disabled = false

[git_branch]
symbol = ""
style = "bg:#eedb85 fg:#212121 bold"
format = ' $symbol$branch'

[git_status]
style = "bg:#eedb85 fg:#212121 bold"
format = '([\[$all_status$ahead_behind\]]($style))'

[character]
success_symbol = " "
error_symbol = " "
